# Generated by Django 4.1.5 on 2023-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("urgency", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
